/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Guru_controller;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author dieka
 */
public class Guru_view extends javax.swing.JFrame {

    /**
     * Creates new form Guru_view
     */
    public Guru_view() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPaneGuru = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKompomen = new javax.swing.JTable();
        tabPaneKompomen = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtEditNama = new javax.swing.JTextField();
        txtEditBobot = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKompomenSimpan = new javax.swing.JButton();
        btnKompomenHapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaEditKeterangan = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTambahNama = new javax.swing.JTextField();
        txtTambahBobot = new javax.swing.JTextField();
        btnKompomenTambah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaTambahKeterangan = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        tabPaneNilai = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        btnNilai = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtNilai = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        lblNamaSiswa = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblKomplain = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();
        tabPaneGuru = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGuruEditNama = new javax.swing.JTextField();
        txtGuruEditUsername = new javax.swing.JTextField();
        txtGuruEditPassword = new javax.swing.JTextField();
        btnGuruSimpan = new javax.swing.JButton();
        btnGuruHapus = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtGuruEditPelajaran = new javax.swing.JTextField();
        chkGuruEditAdmin = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtGuruTambahNama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGuruTambahUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGuruTambahPassword = new javax.swing.JTextField();
        btnGuruTambah = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtGuruTambahPelajaran = new javax.swing.JTextField();
        chkGuruTambahAdmin = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblKelolaSiswa = new javax.swing.JTable();
        tabPaneGuru1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSiswaEditNama = new javax.swing.JTextField();
        txtSiswaEditUsername = new javax.swing.JTextField();
        txtSiswaEditPassword = new javax.swing.JTextField();
        btnSiswaSimpan = new javax.swing.JButton();
        btnSiswaHapus = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtSiswaEditKelas = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtSiswaTambahNama = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSiswaTambahUsername = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtSiswaTambahPassword = new javax.swing.JTextField();
        btnSiswaTambah = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtSiswaTambahKelas = new javax.swing.JTextField();
        panelNama = new javax.swing.JPanel();
        lblNamaGuru = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabPaneGuru.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabPaneGuru.setToolTipText("");
        TabPaneGuru.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblKompomen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKompomen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Kompomen", "Nama Kompomen", "Bobot", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKompomen);
        if (tblKompomen.getColumnModel().getColumnCount() > 0) {
            tblKompomen.getColumnModel().getColumn(0).setMinWidth(0);
            tblKompomen.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblKompomen.getColumnModel().getColumn(0).setMaxWidth(0);
            tblKompomen.getColumnModel().getColumn(3).setMinWidth(0);
            tblKompomen.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblKompomen.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        tabPaneKompomen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEditNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEditBobot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nama Kompomen");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bobot");

        btnKompomenSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKompomenSimpan.setText("Simpan");

        btnKompomenHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKompomenHapus.setText("Hapus");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Keterangan");

        txtAreaEditKeterangan.setColumns(20);
        txtAreaEditKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAreaEditKeterangan.setRows(5);
        jScrollPane4.setViewportView(txtAreaEditKeterangan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(txtEditBobot)
                    .addComponent(txtEditNama))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKompomenHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKompomenSimpan))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnKompomenSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnKompomenHapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEditBobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneKompomen.addTab("Edit Kompomen", jPanel3);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Kompomen");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bobot");

        txtTambahNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTambahBobot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnKompomenTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKompomenTambah.setText("Tambah");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Keterangan");

        txtAreaTambahKeterangan.setColumns(20);
        txtAreaTambahKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAreaTambahKeterangan.setRows(5);
        jScrollPane5.setViewportView(txtAreaTambahKeterangan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(59, 59, 59)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTambahNama)
                    .addComponent(jScrollPane5)
                    .addComponent(txtTambahBobot))
                .addGap(18, 18, 18)
                .addComponent(btnKompomenTambah)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKompomenTambah)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTambahBobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneKompomen.addTab("Tambah Kompomen", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(tabPaneKompomen))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabPaneKompomen)
                .addContainerGap())
        );

        TabPaneGuru.addTab("Kompomen Nilai", jPanel1);

        tabPaneNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblSiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id siswa", "Nama", "Kelas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSiswa);
        if (tblSiswa.getColumnModel().getColumnCount() > 0) {
            tblSiswa.getColumnModel().getColumn(0).setMinWidth(0);
            tblSiswa.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblSiswa.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNilai.setText("Nilai");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNilai)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNilai)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        tabPaneNilai.addTab("Daftar Siswa", jPanel5);

        tblNilai.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_kompomen", "Nama Kompomen", "Nilai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblNilai);
        if (tblNilai.getColumnModel().getColumnCount() > 0) {
            tblNilai.getColumnModel().getColumn(0).setMinWidth(0);
            tblNilai.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblNilai.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nilai");

        txtNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInput.setText("Input");

        lblNamaSiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNamaSiswa.setText("Nama Siswa");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)
                        .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblNamaSiswa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblNamaSiswa)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        tabPaneNilai.addTab("Nilai", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneNilai)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneNilai)
                .addContainerGap())
        );

        TabPaneGuru.addTab("Kelola Nilai", jPanel2);

        tblKomplain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Siswa", "Nama", "Kelas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblKomplain);
        if (tblKomplain.getColumnModel().getColumnCount() > 0) {
            tblKomplain.getColumnModel().getColumn(0).setMinWidth(0);
            tblKomplain.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detil Komplain", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane8.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        TabPaneGuru.addTab("Komplain", jPanel10);

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Guru", "Nama", "Username", "Pelajaran", "admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblGuru);
        if (tblGuru.getColumnModel().getColumnCount() > 0) {
            tblGuru.getColumnModel().getColumn(0).setMinWidth(0);
            tblGuru.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        tabPaneGuru.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nama");

        txtGuruEditNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGuruEditUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGuruEditPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuruSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuruSimpan.setText("Simpan");

        btnGuruHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuruHapus.setText("Hapus");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Pelajaran");

        txtGuruEditPelajaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        chkGuruEditAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkGuruEditAdmin.setText("Admin");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGuruEditPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtGuruEditNama)
                    .addComponent(txtGuruEditUsername)
                    .addComponent(txtGuruEditPassword))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuruSimpan)
                    .addComponent(btnGuruHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGuruEditAdmin))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtGuruEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGuruEditAdmin))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGuruEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGuruEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuruHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuruEditPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnGuruSimpan))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tabPaneGuru.addTab("Edit Guru", jPanel8);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Nama");

        txtGuruTambahNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Username");

        txtGuruTambahUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Password");

        txtGuruTambahPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuruTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuruTambah.setText("Tambah");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Pelajaran");

        txtGuruTambahPelajaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        chkGuruTambahAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkGuruTambahAdmin.setText("Admin");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGuruTambahPelajaran)
                    .addComponent(txtGuruTambahNama)
                    .addComponent(txtGuruTambahUsername)
                    .addComponent(txtGuruTambahPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuruTambah)
                    .addComponent(chkGuruTambahAdmin))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtGuruTambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGuruTambahAdmin))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtGuruTambahUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtGuruTambahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuruTambahPelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btnGuruTambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneGuru.addTab("Tambah Guru", jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabPaneGuru))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabPaneGuru)
                .addContainerGap())
        );

        TabPaneGuru.addTab("Kelola Guru", jPanel7);

        tblKelolaSiswa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKelolaSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id siswa", "Nama", "Kelas", "username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblKelolaSiswa);
        if (tblKelolaSiswa.getColumnModel().getColumnCount() > 0) {
            tblKelolaSiswa.getColumnModel().getColumn(0).setMinWidth(0);
            tblKelolaSiswa.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblKelolaSiswa.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        tabPaneGuru1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Username");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Password");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Nama");

        txtSiswaEditNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSiswaEditUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSiswaEditPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSiswaSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiswaSimpan.setText("Simpan");

        btnSiswaHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiswaHapus.setText("Hapus");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Kelas");

        txtSiswaEditKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSiswaEditNama, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtSiswaEditUsername)
                    .addComponent(txtSiswaEditPassword)
                    .addComponent(txtSiswaEditKelas))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiswaSimpan)
                    .addComponent(btnSiswaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSiswaEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSiswaEditKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(16, 16, 16)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnSiswaHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSiswaSimpan))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtSiswaEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtSiswaEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabPaneGuru1.addTab("Edit Siswa", jPanel13);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Nama");

        txtSiswaTambahNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Username");

        txtSiswaTambahUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Password");

        txtSiswaTambahPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSiswaTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiswaTambah.setText("Tambah");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Kelas");

        txtSiswaTambahKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSiswaTambahNama)
                    .addComponent(txtSiswaTambahUsername)
                    .addComponent(txtSiswaTambahPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtSiswaTambahKelas))
                .addGap(18, 18, 18)
                .addComponent(btnSiswaTambah)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtSiswaTambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSiswaTambahKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtSiswaTambahUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtSiswaTambahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiswaTambah))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabPaneGuru1.addTab("Tambah Siswa", jPanel14);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(tabPaneGuru1))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(tabPaneGuru1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabPaneGuru.addTab("Kelola Siswa", jPanel12);

        panelNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNamaGuru.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNamaGuru.setText("Nama Guru");
        lblNamaGuru.setName("lblNamaGuru"); // NOI18N

        javax.swing.GroupLayout panelNamaLayout = new javax.swing.GroupLayout(panelNama);
        panelNama.setLayout(panelNamaLayout);
        panelNamaLayout.setHorizontalGroup(
            panelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNamaGuru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNamaLayout.setVerticalGroup(
            panelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNamaGuru)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabPaneGuru))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TabPaneGuru)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guru_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPaneGuru;
    private javax.swing.JButton btnGuruHapus;
    private javax.swing.JButton btnGuruSimpan;
    private javax.swing.JButton btnGuruTambah;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnKompomenHapus;
    private javax.swing.JButton btnKompomenSimpan;
    private javax.swing.JButton btnKompomenTambah;
    private javax.swing.JButton btnNilai;
    private javax.swing.JButton btnSiswaHapus;
    private javax.swing.JButton btnSiswaSimpan;
    private javax.swing.JButton btnSiswaTambah;
    private javax.swing.JCheckBox chkGuruEditAdmin;
    private javax.swing.JCheckBox chkGuruTambahAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblNamaGuru;
    private javax.swing.JLabel lblNamaSiswa;
    private javax.swing.JPanel panelNama;
    private javax.swing.JTabbedPane tabPaneGuru;
    private javax.swing.JTabbedPane tabPaneGuru1;
    private javax.swing.JTabbedPane tabPaneKompomen;
    private javax.swing.JTabbedPane tabPaneNilai;
    private javax.swing.JTable tblGuru;
    private javax.swing.JTable tblKelolaSiswa;
    private javax.swing.JTable tblKomplain;
    private javax.swing.JTable tblKompomen;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTable tblSiswa;
    private javax.swing.JTextArea txtAreaEditKeterangan;
    private javax.swing.JTextArea txtAreaTambahKeterangan;
    private javax.swing.JTextField txtEditBobot;
    private javax.swing.JTextField txtEditNama;
    private javax.swing.JTextField txtGuruEditNama;
    private javax.swing.JTextField txtGuruEditPassword;
    private javax.swing.JTextField txtGuruEditPelajaran;
    private javax.swing.JTextField txtGuruEditUsername;
    private javax.swing.JTextField txtGuruTambahNama;
    private javax.swing.JTextField txtGuruTambahPassword;
    private javax.swing.JTextField txtGuruTambahPelajaran;
    private javax.swing.JTextField txtGuruTambahUsername;
    private javax.swing.JTextField txtNilai;
    private javax.swing.JTextField txtSiswaEditKelas;
    private javax.swing.JTextField txtSiswaEditNama;
    private javax.swing.JTextField txtSiswaEditPassword;
    private javax.swing.JTextField txtSiswaEditUsername;
    private javax.swing.JTextField txtSiswaTambahKelas;
    private javax.swing.JTextField txtSiswaTambahNama;
    private javax.swing.JTextField txtSiswaTambahPassword;
    private javax.swing.JTextField txtSiswaTambahUsername;
    private javax.swing.JTextField txtTambahBobot;
    private javax.swing.JTextField txtTambahNama;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(Guru_controller gc) {
        btnKompomenHapus.addActionListener(gc);
        btnKompomenSimpan.addActionListener(gc);
        btnKompomenTambah.addActionListener(gc);
        
        btnInput.addActionListener(gc);
        btnNilai.addActionListener(gc);
        
        btnGuruSimpan.addActionListener(gc);
        btnGuruHapus.addActionListener(gc);
        btnGuruTambah.addActionListener(gc);
        
        btnSiswaSimpan.addActionListener(gc);
        btnSiswaHapus.addActionListener(gc);
        btnSiswaTambah.addActionListener(gc);
    }
    
    public void addListSelectionListener(Guru_controller gc){
        tblKompomen.getSelectionModel().addListSelectionListener(gc);
        tblNilai.getSelectionModel().addListSelectionListener(gc);
        tblGuru.getSelectionModel().addListSelectionListener(gc);
        tblKelolaSiswa.getSelectionModel().addListSelectionListener(gc);
    }
    
    public void addChangeListener(Guru_controller gc){
        tabPaneNilai.addChangeListener(gc);
        tabPaneGuru.addChangeListener(gc);
    }

    public JLabel getLblNamaGuru() {
        return lblNamaGuru;
    }

    public JTable getTblKompomen() {
        return tblKompomen;
    }

    public JButton getBtnKompomenHapus() {
        return btnKompomenHapus;
    }

    public JButton getBtnKompomenSimpan() {
        return btnKompomenSimpan;
    }

    public JButton getBtnKompomenTambah() {
        return btnKompomenTambah;
    }

    public JTextField getTxtEditBobot() {
        return txtEditBobot;
    }

    public JTextField getTxtEditNama() {
        return txtEditNama;
    }

    public JTextField getTxtTambahBobot() {
        return txtTambahBobot;
    }

    public JTextField getTxtTambahNama() {
        return txtTambahNama;
    }

    public JTextArea getTxtAreaEditKeterangan() {
        return txtAreaEditKeterangan;
    }

    public JTextArea getTxtAreaTambahKeterangan() {
        return txtAreaTambahKeterangan;
    }

    public JTabbedPane getTabPaneGuru() {
        return TabPaneGuru;
    }

    public JTabbedPane getTabPaneKompomen() {
        return tabPaneKompomen;
    }

    public JTabbedPane getTabPaneNilai() {
        return tabPaneNilai;
    }

    public JTable getTblSiswa() {
        return tblSiswa;
    }

    public JTable getTblNilai() {
        return tblNilai;
    }

    public JTextField getTxtNilai() {
        return txtNilai;
    }

    public JButton getBtnInput() {
        return btnInput;
    }

    public JButton getBtnNilai() {
        return btnNilai;
    }

    public JLabel getLblNamaSiswa() {
        return lblNamaSiswa;
    }

    public JButton getBtnGuruHapus() {
        return btnGuruHapus;
    }

    public JButton getBtnGuruSimpan() {
        return btnGuruSimpan;
    }

    public JButton getBtnGuruTambah() {
        return btnGuruTambah;
    }

    public JTable getTblGuru() {
        return tblGuru;
    }

    public JTable getTblKomplain() {
        return tblKomplain;
    }

    public JTextField getTxtGuruTambahNama() {
        return txtGuruTambahNama;
    }

    public JTextField getTxtGuruTambahPassword() {
        return txtGuruTambahPassword;
    }

    public JTextField getTxtGuruTambahUsername() {
        return txtGuruTambahUsername;
    }

    public JTextField getTxtGuruEditNama() {
        return txtGuruEditNama;
    }

    public JTextField getTxtGuruEditPassword() {
        return txtGuruEditPassword;
    }

    public JTextField getTxtGuruEditUsername() {
        return txtGuruEditUsername;
    }

    public JTextField getTxtGuruEditPelajaran() {
        return txtGuruEditPelajaran;
    }

    public JTextField getTxtGuruTambahPelajaran() {
        return txtGuruTambahPelajaran;
    }

    public JCheckBox getChkGuruEditAdmin() {
        return chkGuruEditAdmin;
    }

    public JCheckBox getChkGuruTambahAdmin() {
        return chkGuruTambahAdmin;
    }

    public JButton getBtnSiswaHapus() {
        return btnSiswaHapus;
    }

    public JButton getBtnSiswaSimpan() {
        return btnSiswaSimpan;
    }

    public JButton getBtnSiswaTambah() {
        return btnSiswaTambah;
    }

    public JTextField getTxtGuruEditNama1() {
        return txtSiswaEditNama;
    }

    public JTextField getTxtGuruEditPassword1() {
        return txtSiswaEditPassword;
    }

    public JTextField getTxtGuruEditPelajaran1() {
        return txtSiswaEditKelas;
    }

    public JTextField getTxtGuruEditUsername1() {
        return txtSiswaEditUsername;
    }

    public JTextField getTxtSiswaTambahKelas() {
        return txtSiswaTambahKelas;
    }

    public JTextField getTxtSiswaTambahNama() {
        return txtSiswaTambahNama;
    }

    public JTextField getTxtSiswaTambahPassword() {
        return txtSiswaTambahPassword;
    }

    public JTextField getTxtSiswaTambahUsername() {
        return txtSiswaTambahUsername;
    }

    public JTable getTblKelolaSiswa() {
        return tblKelolaSiswa;
    }

    public JTextField getTxtSiswaEditNama() {
        return txtSiswaEditNama;
    }

    public JTextField getTxtSiswaEditPassword() {
        return txtSiswaEditPassword;
    }

    public JTextField getTxtSiswaEditKelas() {
        return txtSiswaEditKelas;
    }

    public JTextField getTxtSiswaEditUsername() {
        return txtSiswaEditUsername;
    }

    
}
